import './globals.css';
import { Inter } from 'next/font/google';
import Nav from './components/Nav';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Webshop Next Projekt',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
