'use client'
import './globals.css';
import { Inter } from 'next/font/google';
import Nav from './components/Nav';
import Footer from './components/Footer';
import { ThemeProvider } from '@material-tailwind/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Webshop Next Projekt',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<ThemeProvider>
					<Nav />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
