version: '3.9'

services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    restart: always
    depends_on:
      - server
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:hardwell86@cube:5432/postgres?schema=public
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hardwell86
      POSTGRES_DB: cube
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
