import './globals.css'
import { Inter } from 'next/font/google'
import { RecoilRoot } from 'recoil'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Leetcode Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<RecoilRoot>
			<html lang='en'>
				<body className={inter.className}>{children}</body>
			</html>
		</RecoilRoot>
	);
}
