import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Categorys from './components/Categorys'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bookshop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html
			lang='en'
			className='bg-[#030711] ml-[20rem] mr-[20rem]'
		>
			<body className={inter.className}>
				<Navbar />
				<Categorys />
				{children}
				<Footer />
			</body>
		</html>
	);
}
